GET http://localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYXJ5YW4iLCJpYXQiOjE2Njk0NTQ5NDl9.0sKDIUSIsPNTjsBq7uIIFgxc3LZTP_NYpEu-Z53JeFg
###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "aryan"
}