GET http://localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYXJ5YW4iLCJpYXQiOjE2Njk0NTcxMjYsImV4cCI6MTY2OTQ1NzE1Nn0.hvVZVj1hOjXJlCxsXlk61m5Zz2L8YtjuAcWHClnFO18



###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "aryan"
}